  services:
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "55432:80"
      env_file:
        - .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - backend_network

  networks:
    backend_network:
      driver: bridge

  volumes:
    postgres_data:
    pgadmin_data: