  services:
    postgres:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports:
        - "5432:5432"
      env_file:
        - .env
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - backend_network

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "55432:80"
      env_file:
        - .env
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      networks:
        - backend_network

  networks:
    backend_network:
      driver: bridge

  volumes:
    postgres_data:
    pgadmin_data: